# Generated by Django 4.1.7 on 2023-04-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='defaultimage.png', null=True, upload_to='Product_Image/'),
        ),
    ]
